spring:
 application:
   name: CARBURANT-SERVICE
   Description: TajiSugu carburant microservice
 profiles:
   active: test
  
db:
   connection: "{connectionString:'http://___',userName:'', password:''}"
    host: 
     port: 
   
 server:
  port: 0

eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761
   management.endpoints.web.exposure.include: "*"
