app:
   name: CONFIG-SERVER
   Description: TajiSugu config server microservice
  
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka 

