spring:
 application:
  name: eureka
 profiles:
  active: test
 eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 profiles:
   active: test     
server:
   port: 8761
