spring:
 application:
  name: EUREKA-SERVICE
 eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 profiles:
   active: PRODUCTION
server:
   port: 8761
